### ISSUE TITLE
Feature Request: Make the app native-image ready

### ISSUE THREAD

**Issue by renedupont** [eska-muc/dbvisualizer#12]
Hello,
not sure if you'd be interested at all in that topic, but I played around with your tool to compile it [natively with GraalVM](https://www.graalvm.org/22.0/reference-manual/native-image/). 
Basically I 
- exchanged the logging dependency because log4j is not well suited for native-image builds
- added a reflect-config.json with all required classes that are unknown at build-time
- the big trade-off seems to be that a native executable can't load jar files during runtime, therefore if someone wants to compile native, he has to include the required db drivers beforehand. In my case, I added the postgresql driver as dependency to pom.xml and had to add some classes of that to the reflect-config.json file.

Again, let me know if you'd be interested in that topic and I'll send a PR extending your readme with the required infos for users that want to do this as well.

**Comment by eska-muc** [comment]
Hi René,
sounds interesting, so an additional chapter in the README.md or - maybe - also an additional file would be nice. So please create a PR. For logging I've just used log4j because I was quite familar with it. What alternative did you use?
