### ISSUE TITLE
Lost Focus while writing in SqlCommander windows

### ISSUE THREAD

**Issue by ciroppina** [eska-muc/dbvisualizer#8]
Every 24 seconds, the focus gets lost, even while I am writing a statement;
I noticed the focus "goes" up to the current tab title;
thank You

Product: DbVisualizer Pro 13.0.3 [EVALUATION] (build: 3265)
OS: Windows 10
OS Version: 10.0
OS Arch: amd64
Java Version: 11.0.14
Java VM: OpenJDK 64-Bit Server VM
Java Vendor: Eclipse Adoptium
Java Home: c:\program files\dbvisualizer\jre
DbVis Home: C:\Program Files\DbVisualizer
User Home: C:\Users\Utente
PrefsDir: C:\Users\Utente\.dbvis
SessionId: 421
BindDir: C:\Users\Utente\.dbvis\[2]

**Comment by eska-muc** [comment]
You probably confused the repo with some different tool. This software does not have a UI at all.
